### ISSUE TITLE
Alcinoe and Delphi 11

### ISSUE THREAD

**Issue by gonzzzales** [MagicFoundation/Alcinoe#221]
Is it possible to use components with Delphi 11. I tryed to use it, as with 10.4.2, but get errors like this 
[DCC Fatal Error] FMX.Platform.iOS.pas(17): F2051 Unit Macapi.MetalKit was compiled with a different version of iOSapi.UIKit.UIViewClass

Please, help me!!!

**Comment by marlonnardi** [comment]
Hello @Zeus64  how are you?  hope so.  I would like Feedback from you regarding updates to Delphi 11. I say this because I know the Alcione project is complex and you have no obligation to keep it up to date, so it's on GitHub to get improvements, but like else we know, so far only you have the domain to update and improve the project.  I would just like to know if you are going to upgrade to Delphi 11 or not.  If you don't upgrade I'll have to migrate all Alcione components to native, something I didn't want as Alcione components are fantastic and extremely performant, but I need to upgrade to Delphi 11 which has support for the new XCode and IOS 15 , I have many customers that are with this version and the applications built with Delphi 10.4.2 is no longer supported.
![81983B4F-4AC2-4813-8048-EF174EB41771](https://user-images.githubusercontent.com/5359931/139537780-d5747d3d-81b9-4e3b-82a9-6ad07dcac1df.png)

**Comment by Zeus64** [comment]
Hi, yes I m updating to Delphi 11. Support will be added soon with the release of the update 1 of Delphi 11

**Comment by marlonnardi** [comment]
> Hi, yes I m updating to Delphi 11. Support will be added soon with the release of the update 1 of Delphi 11

Perfect!!! I'm looking forward to it

**Comment by gabrieldeoliveira96** [comment]
Hi, I built my app using alcinoe components, they were working perfectly!
but google changed its minimum version for sending apps,
now with API 30 i need to compile my app in ​​Delphi 11...
I'm getting the following error when compiling:
"raised EJNIFatal exception class with message 'Java type with / alcinoe / edittext / ALKeyPreImeListener could not be found'."

I would like to know if there is any forecast to migrate the project from alcinoé to Delphi 11

Thank you very much!

![imagem_2021-11-03_164945](https://user-images.githubusercontent.com/29439325/140182329-26c3bdba-759b-40bf-bb05-6dc80eefcf65.png)

**Comment by gonzzzales** [comment]
Hello **@Zeus64**, how is the work on the update progressing? Сan you tell us about timings? 
Best Regards!!!

**Comment by marlonnardi** [comment]
> Hi, yes I m updating to Delphi 11. Support will be added soon with the release of the update 1 of Delphi 11

Hi @Zeus64 

What updates are you waiting for in Delphi 11 Update 1 to perform this alcinoe update?

is it any specific RSP?

**Comment by JerryMacNow** [comment]
Hi @Zeus64.

I have a question that probably a lot of other people want to ask.
What are the chances for an update for Delphi 11 ?
Are you able to give an approximate date?

It is important to me if it is worth waiting.

Greetings

Jerry

**Comment by Zeus64** [comment]
Hi, I follow the rule to wait at least one major update (update 1) before to merge all the modifications. Normally the update 1 arrive around 2-3 months after the initial release. I do this because it's time intensive to merge everything and I prefer to wait a stable release (ie update 1 at least) before to to all the job.

**Comment by JerryMacNow** [comment]
Thank you for writing back.
I understand. I don't hold it against you. Thanks a lot for the project !

The first update to Delphi 11 was over a month ago. 
I understand that you need about 1-2 more months, yes ?

**Comment by GitUserMarkus** [comment]
@JerryMacNow I think you are confusing upadate (which is sort of a set of patches) and release-update which would make embacadero name Delphi 11 then Delphi 11.1
As I understand, Zeus64 for good reasons waits for Delphi 11.1 and hopefully he is right that we can expect this new release to be published soon for many of us seem to need Alcinoe to be available for Delphi 11.

**Comment by JerryMacNow** [comment]
@GitUserMarkus 
Thank you for the clarification.  Although it is not good news.

**Comment by duhan2007** [comment]
After I have manually patched and produced the required D11 libraries, I could installed Alcinoe to delphi 11 and all demos seems working fine for now (especially ALfmxControls demo ;)  )

**Comment by GitUserMarkus** [comment]
Sounds great! Can you provide a download?

**Comment by marlonnardi** [comment]
> After I have manually patched and produced the required D11 libraries, I could installed Alcinoe to delphi 11 and all demos seems working fine for now (especially ALfmxControls demo ;)  )

share the files you modified, have you tested for iOS too?

**Comment by marlonnardi** [comment]
for those who need a temporary solution, follow the updated files, for D11 compilation.

[Alcinoe_alexandria.zip](https://github.com/Zeus64/alcinoe/files/7878960/Alcinoe_alexandria.zip)

**Comment by GitUserMarkus** [comment]
I have patched the D11 source files manually according to the information provided in the git-diff-file provided by Zeus for D10.4. Now I can compile my project for iOS, however, I get the following linking-error: [DCC Fataler Fehler] F2588 Linker-Fehlercode: 3221225477 ($c0000005)
Any idea what went wrong?

**Comment by JerryMacNow** [comment]
Hi @GitUserMarkus  !
Can you describe to me what needs to be done to run the libraries on Delphi 11. I would be very grateful for your help

**Comment by JerryMacNow** [comment]
I managed to get it to work under Delphi 11. But I can't get the Video Player to work, and that's very important for me. Do you have any way to do it ?

**Comment by Zeus64** [comment]
Hi everyone sorry for the delay I m actually under the water with different projects :( I planed to update alcinoe with the Update 1 of Alexandria that must be released soon. Why update 1? because unfortunately I patched the source code and reporting the modifications to a new release of delphi is really a pain, even between minor update of delphi. so I always wait a minor update of a major release before to spend days in the migration. @JerryMacNow what is not working exactly? video player absolutely need the delphi source patched especially to work under Android (because it's need to support ExternalOESTextureMaterial). @GitUserMarkus and marlonnardi thanks for you help :)

**Comment by JerryMacNow** [comment]
@Zeus64  - I can hear the sound, but the image is fuzzy and distorted.
For IOS I can't compile your example under Delphi 11 :/

**Comment by JerryMacNow** [comment]
Then I have this question. I'm back to Delphi 10.4.2 and have done an IOS SDK update to version 15.2.
I am using a server in MacInCloud with macOS Monterey to compile.

During compilation I get the following error. 
[DCC Error] E2597 ld: warning: directory not found for option '-FC:UserDocumentsEmbarcaderoStudioSDKsSystemLibraryPrivateFrameworksDocumentManager.framework'
  ld: file not found: /usr/lib/system/libcache.dylib for architecture arm64
[DCC Fatal Error] F2588 Linker error code: 1 ($00000001)

What can be done about it ?

**Comment by firemen01** [comment]
RAD 11.1 released.
 
https://altd.embarcadero.com/download/radstudio/11.0/RADStudio_11_1_esd_10_8973a.iso

**Comment by commanderz** [comment]
just added patched files for compile alcicoe for Delphi 11 Alexandria
https://github.com/commanderz/alcinoe-delphi11-patched
@Zeus64 can use it free if want, and tnanks you, bro, for very cool lib.

**Comment by Zeus64** [comment]
thanks everyone, alcinoe is now fully compatible with alexandria

**Comment by Tiagoadvir** [comment]
I have some problems with Alcinoa in delphi 10.4.2, i has installed but, to compile a has the message :
[dcc32 Error] Alcinoe.FMX.Layouts.pas(144): E2137 Method 'ChildrenMouseDown' not found in base class, some one can help me?
