### ISSUE TITLE
Delphi 11.2: ALVideoPlayer in IOS

### ISSUE THREAD

**Issue by VanarGames** [MagicFoundation/Alcinoe#300]
Hello,
I can't show video under IOS on Delphi 11.2.

The video is not shown, I hear only the sound from this video.
Black screen instead of video
Tried on Demo: ALFmxControls
And
procedure TForm2.Button2Click(Sender: TObject);
begin
  If ALVideoPlayerSurface.VideoPlayer.state in [vpsIdle] Then
   ALVideoPlayerSurface.VideoPlayer.prepare('http://techslides.com/demos/samples/sample.mp4', True);
end;
The result is the same: Black screen and sound

**Comment by VanarGames** [comment]
And in Delphi 11.3 CE too

**Comment by Zeus64** [comment]
I was able to reproduce, i will work on it asap

**Comment by havrlisan** [comment]
Not sure if you've got onto this yet, but because of Skia you won't be able to use _TCustomCanvasGpu_ in _TALVideoPlayerSurface.Paint_ anymore. Perhaps it'd be a good idea to recreate your _TALVideoPlayerSurface_  control to inherit from TViewport3D, and then create an inner control that inherits from _TShape3D_ whose _MaterialSource_ will be _TTextureMaterialSource_? That way you'll again have direct access to a TTexture property via _TTextureMaterial(TTextureMaterialSource.Material).Texture_ that will trigger Repaint on change in its setter.

Hope I helped!

**Comment by Zeus64** [comment]
Hi, i m on it right now, i m doing the migration to Athens. hope I will finish this week or new week
