### ISSUE TITLE
Add support for ReadOnly in TALEdit / TALMemo

### ISSUE THREAD

**Issue by maurobotta** [MagicFoundation/Alcinoe#346]
Hi

Is possibile Add support for ReadOnly in TALEdit / TALMemo ?

Like Enabled False but not gray.... 

Thank you.

**Comment by Zeus64** [comment]
Hello, TALEdit and TALMemo are simply wrappers for the native OS edit/memo components (like EditText on Android, UITextField on iOS, NSTextField on macOS, and Edit on Windows). The issue is that ReadOnly is not natively supported by all platforms. For example, on Android, you must set the enabled property to false, as there is no ReadOnly property. Personally, I always find it a bit confusing to have an edit control that looks exactly like a regular one but doesn’t allow editing. It feels more intuitive to have the edit field grayed out to indicate that input is disabled.

However, if you want this ReadOnly feature, you can implement it in the master branch and submit a pull request (PR). I'll approve it, but before doing so, consider if setting enabled = false might be a better alternative than introducing ReadOnly = false.
