### ISSUE TITLE
WordWrap on TALText / TALEdit / TALMemo

### ISSUE THREAD

**Issue by maurobotta** [MagicFoundation/Alcinoe#360]
Hi @Zeus64 , I have 2 questions. 

1) I have TALText, How work WordWrap ?

myLabel.TextSettings.WordWrap := False;       <<- don't exit

2) See bottom Image, how i hidden ".." in Label / Memo / Edit ? i need see ALL TEXT without cut.

Thank you again for your work and commitment. 
Alcinoe is number one.

Mauro

![image](https://github.com/user-attachments/assets/98d0ecbc-f311-470f-a349-a95683e3dd7e)

**Comment by Zeus64** [comment]
Hi maurobotta,

1.
>I have TALText, How work WordWrap ?

in TALText the wordwrap is done in Textsettings.MaxLines. 
MaxLines = 1 mean no wordwrap, MaxLines > 1 mean wordwrap. by default MaxLines = 65535 so it's mean wordwrap

2.
> See bottom Image, how i hidden ".." in Label / Memo / Edit ? i need see ALL TEXT without cut.

if you want to see all text without cut, you must set MyText.autosize = true so that the control will resize to fit all the text
