### ISSUE TITLE
install

### ISSUE THREAD

**Issue by roozgar** [MagicFoundation/Alcinoe#8]
hii
is there an install document !?

**Comment by arvanus** [comment]
Hi! I couldn't find one... but I figured what to do to install and build samples for android (Delphi tokyo):
Install latest java 1.7 AND 1.8, android  SDK of Oreo (27)
edit compilejar_tokyo.bat lines 19-23 
and fix line 46 from
`%JDK_PATH%\javac -source 1.7 -target 1.7 -bootclasspath %JDK_PATH1_7%\jre\lib\rt.jar -Xlint:unchecked -Xlint:deprecation -cp^`
to
`%JDK_PATH%\javac -source 1.7 -target 1.7 -bootclasspath %JDK_PATH1_7%\..\jre\lib\rt.jar -Xlint:unchecked -Xlint:deprecation -cp^
`

note "..\"


from CMD run compile_tokyo... (I didnt build demos)
than, with your Delphi, open source\Alcinoe_tokyo.dproj, build and install the components and add library paths!
It's it

**Comment by checkdigits** [comment]
Hi, kind of relevant to this I am planning on creating a pull request which will include a full and automated signed installer for the components and files in this project.

This is with a view to including this library in the GetIt Package Manager in Delphi 10.3 Rio (and perhaps others).  Part of my contribution to Delphi is to liaise with open source component teams and help get them listed on GetIt.  To do that though it really needs an installer to help automate the process - and since there isn't one at the moment I'm happy to help create one.  For Windows users it is preferable that the installer binary is code-signed - I can make that happen too.

![image](https://user-images.githubusercontent.com/2126394/51094518-684c0080-1773-11e9-8ae5-48a784b8995b.png)

Embarcadero are pretty keen to see Alcinoe made available via GetIt - it's a great set of components with some quite unique features. 😃 

![image](https://user-images.githubusercontent.com/2126394/51094534-86b1fc00-1773-11e9-8832-13ccbc1d1597.png)

Keep up the good work! 👍

**Comment by checkdigits** [comment]
Perhaps our understanding of GetIt is different to yours.  GetIt really just automates the finding and running of any installer that there is.  It also manages some dependencies too but this is not always necessary.

What I am suggesting is that *if* there is an installer or an installer could be created (even by me) then we could make the Alcinoe library available by GetIt.

The strength of GetIt is that it can make it easy to find out about great libraries like Alcinoe and help Delphi users get a copy of the latest download.  I can help make that happen, for all relevant versions of Delphi/RAD Studio.

I recognize that what you are saying is that *right now* the library requires 'too much extra work before it can be used' and I understand that - but I am also saying that a lot of people were VERY impressed with the YouTube demo of the dating app and thought that the Alcinoe library was something they would be interested in.

If I can help make that happen then I'd be glad to do so.  I've already put in one pull request for some minor corrections to the documentation.

If you do collectively decide that GetIt is either impossible due to requiring too much extra work or that you don't want the library in GetIt for other reasons then that's totally OK.  😃 

Meanwhile, a great library, good work! 👍

**Comment by cunhajr** [comment]
Hi,  I just found alcinoe components a few days ago.  I would like to use it. I am having this issue:
"[DCC Fatal Error] FMX.ListView.pas(5822): F2051 Unit Fmx.Bind.Editors was compiled with a different version of FMX.ListView.TCustomListView "

My alcinoe installation:
1) Downgrade to Tokyo, I am using Rio, but it is fine use Tokyo to use Alcinoe.
2) O changed my sdk android to Android 9 (28)
3) I backup all berlin's fmx units  and replaced the originals with the alcinoe patched units.  ( I tryed to just add the alcinoe patched path to the library path but I was getting a lot of different version compiled unit )

With this 3 steps above, I can build all alcinoe demos.  But I open my actual project and I got this error.

What I did wrong ?  

Thanks @Zeus64  for this great work!

**Comment by checkdigits** [comment]
@cunhajr Delete all the DCUs in your _project's_ folder and then select build all.

The error you are describing usually results from having some search paths which point to a folder which has DCUs for your own code which was built with a different version of Delphi and have not got rebuilt from the .PAS files.

**Comment by cunhajr** [comment]
@checkdigits thanks I will check the DCUs

I was thinking that my issue is related the way I installed alcinoe, I didn't recompiled it using the compile_tokyo.bat, due the MSBUILD6002 error with max_path,  I have two delphis ( Tokyio and Rio ) on my computer and maybe this is causing the problem with msbuild.

I will double check the dcu as you sugested @checkdigits  but I have a doubt about the patched fmx folder. Should I copy the files to fmx delphi folder ?

Thanks a lot.

**Comment by soonsam123** [comment]
I was able to install it in tokyo even though I also have rio installed on my pc

**Comment by checkdigits** [comment]
Ah I think you might have to resolve the issue with MAXPATH first - I didn’t notice that you’d not recompiled using MSBuild; you’ll need to do that for it to work ☹️

**Comment by cunhajr** [comment]
I tried everything to fix this:
Microsoft (R) Build Engine Version 3.5.30729.8931
[Microsoft .NET Framework, Version 2.0.50727.8940]
Copyright (C) Microsoft Corporation 2007. All rights reserved.

Build started 12/05/2019 11:39:33.
Project "c:\alcinoe-master\source\Alcinoe_tokyo.dproj" on node 0 (default targets).
C:\Program Files (x86)\Embarcadero\Studio\19.0\Bin\CodeGear.Delphi.Targets : warning MSB6002: The command-line for the
"DCC" task is too long. Command-lines longer than 32000 characters are likely to fail. Try reducing the length of the c
ommand-line by breaking down the call to "DCC" into multiple calls with fewer parameters per call.
C:\Program Files (x86)\Embarcadero\Studio\19.0\Bin\CodeGear.Delphi.Targets(399,5): error MSB6003: The specified task ex
ecutable "dcc" could not be run. O nome do arquivo ou a extensão é muito grande
Done Building Project "c:\alcinoe-master\source\Alcinoe_tokyo.dproj" (default targets) -- FAILED.


Build FAILED.

"c:\alcinoe-master\source\Alcinoe_tokyo.dproj" (default target) (1) ->
(_PasCoreCompile target) ->
  C:\Program Files (x86)\Embarcadero\Studio\19.0\Bin\CodeGear.Delphi.Targets : warning MSB6002: The command-line for th
e "DCC" task is too long. Command-lines longer than 32000 characters are likely to fail. Try reducing the length of the
 command-line by breaking down the call to "DCC" into multiple calls with fewer parameters per call.


"c:\alcinoe-master\source\Alcinoe_tokyo.dproj" (default target) (1) ->
(_PasCoreCompile target) ->
  C:\Program Files (x86)\Embarcadero\Studio\19.0\Bin\CodeGear.Delphi.Targets(399,5): error MSB6003: The specified task
executable "dcc" could not be run. O nome do arquivo ou a extensão é muito grande

    1 Warning(s)
    1 Error(s)

**Comment by checkdigits** [comment]
Ok I see what you mean. I’m currently not at my office so I can’t give you a specific answer. It should be fixable though, it’s just the pathnames (I think) when expanded are too long.

**Comment by Zeus64** [comment]
Hi, everything is now documented in the ReadMe.md at https://github.com/MagicFoundation/Alcinoe
